import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.product import ProductCondition


class ProductImageRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    product_id: uuid.UUID
    sort_order: int
    media_type: str = "image"
    is_cover: bool = False
    s3_bucket: str
    s3_key: str
    filename: str | None
    content_type: str | None
    size_bytes: int | None
    created_at: datetime
    url: str | None = None  # filled by API when serializing


class ProductImageUpdate(BaseModel):
    """PATCH body for /products/{id}/images/{image_id}."""

    is_cover: bool | None = None


class ProductImageFromUrlCreate(BaseModel):
    """POST body for /products/{id}/images/from-url (images only)."""

    url: str = Field(min_length=8, max_length=2048)
    is_cover: bool = False


class ProductCore(BaseModel):
    """Product fields excluding SKU (SKU is server-assigned on create, immutable thereafter)."""

    title: str = Field(min_length=1, max_length=500)
    description: str | None = None
    condition: ProductCondition
    brand_id: uuid.UUID | None = None
    model: str | None = Field(None, max_length=255)
    category_id: uuid.UUID | None = None
    colour: str | None = Field(None, max_length=255)
    length_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    width_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    depth_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    base_price: Decimal = Field(ge=0, decimal_places=2)
    compare_at_price: Decimal | None = Field(None, ge=0, decimal_places=2)
    quantity: int = Field(ge=0, default=1)
    attributes: dict[str, Any] | None = None
    status: str = Field(default="active", max_length=32)
    active: bool = True

    @field_validator("colour", mode="before")
    @classmethod
    def _blank_colour_none(cls, v: object) -> str | None:
        if v is None:
            return None
        s = str(v).strip()
        return s or None


class ProductBase(ProductCore):
    sku: str = Field(min_length=1, max_length=128)


class ProductCreate(ProductCore):
    """POST /products — SKU is generated by the API; clients must not send sku."""

    model_config = ConfigDict(extra="forbid")


class ProductUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    title: str | None = Field(None, min_length=1, max_length=500)
    description: str | None = None
    condition: ProductCondition | None = None
    brand_id: uuid.UUID | None = None
    model: str | None = None
    category_id: uuid.UUID | None = None
    colour: str | None = Field(None, max_length=255)
    length_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    width_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    depth_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    base_price: Decimal | None = Field(None, ge=0, decimal_places=2)
    compare_at_price: Decimal | None = Field(None, ge=0, decimal_places=2)
    quantity: int | None = Field(None, ge=0)
    attributes: dict[str, Any] | None = None
    status: str | None = Field(None, max_length=32)
    active: bool | None = None

    @field_validator("colour", mode="before")
    @classmethod
    def _blank_colour_none_update(cls, v: object) -> str | None:
        if v is None:
            return None
        s = str(v).strip()
        return s or None


class ProductRead(ProductBase):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    organisation_id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    created_by_user_id: uuid.UUID | None = None
    updated_by_user_id: uuid.UUID | None = None
    created_by_label: str | None = None
    updated_by_label: str | None = None
    images: list[ProductImageRead] = []
    brand_name: str | None = None  # set by API from ryunova_brands


class ProductListPage(BaseModel):
    """Paginated product list (GET /products)."""

    items: list[ProductRead]
    total: int = Field(ge=0)
    page: int = Field(ge=1)
    page_size: int
    total_pages: int = Field(ge=1)
