import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, field_validator

from app.models.product import ProductCondition
from app.schemas.listing_channel import ProductMarketplaceListingRead

ListingReadiness = Literal["draft", "ready_to_post"]


class ProductImageRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    product_id: uuid.UUID
    sort_order: int
    media_type: str = "image"
    is_cover: bool = False
    s3_bucket: str
    s3_key: str
    filename: str | None
    content_type: str | None
    size_bytes: int | None
    created_at: datetime
    url: str | None = None  # filled by API when serializing


class ProductImageUpdate(BaseModel):
    """PATCH body for /products/{id}/images/{image_id}."""

    is_cover: bool | None = None


class ProductImageFromUrlCreate(BaseModel):
    """POST body for /products/{id}/images/from-url (images only)."""

    url: str = Field(min_length=8, max_length=2048)
    is_cover: bool = False


class ProductCore(BaseModel):
    """Product fields excluding SKU (SKU is server-assigned on create, immutable thereafter)."""

    title: str = Field(min_length=1, max_length=500)
    description: str | None = None
    condition: ProductCondition
    brand_id: uuid.UUID | None = None
    model: str | None = Field(None, max_length=255)
    category_id: uuid.UUID | None = None
    colour: str | None = Field(None, max_length=255)
    length_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    width_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    depth_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    weight_kg: Decimal | None = Field(None, ge=0, decimal_places=3) # NEW
    base_price: Decimal = Field(ge=0, decimal_places=2)
    compare_at_price: Decimal | None = Field(None, ge=0, decimal_places=2)
    cost_price: Decimal | None = Field(None, ge=0, decimal_places=2) # NEW
    quantity: int = Field(ge=0, default=1)
    allow_oversell: bool = False # NEW
    attributes: dict[str, Any] | None = None
    status: str = Field(default="active", max_length=32)
    listing_readiness: ListingReadiness = "draft"
    active: bool = True
    currency_code: str = Field(default="AUD", min_length=3, max_length=3)

    # Global Identifiers
    barcode: str | None = Field(None, max_length=255) # NEW
    hs_code: str | None = Field(None, max_length=64) # NEW

    @field_validator("colour", "barcode", "hs_code", mode="before")
    @classmethod
    def _blank_colour_none(cls, v: object) -> str | None:
        if v is None:
            return None
        s = str(v).strip()
        return s or None

    @field_validator("currency_code", mode="before")
    @classmethod
    def _currency_upper(cls, v: object) -> str:
        s = str(v or "AUD").strip().upper()
        return s if len(s) == 3 else "AUD"


class ProductBase(ProductCore):
    sku: str = Field(min_length=1, max_length=128)


class ProductCreate(ProductCore):
    """POST /products — SKU is generated by the API; clients must not send sku."""

    model_config = ConfigDict(extra="forbid")


class ProductUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    title: str | None = Field(None, min_length=1, max_length=500)
    description: str | None = None
    condition: ProductCondition | None = None
    brand_id: uuid.UUID | None = None
    model: str | None = None
    category_id: uuid.UUID | None = None
    colour: str | None = Field(None, max_length=255)
    length_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    width_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    depth_cm: Decimal | None = Field(None, ge=0, decimal_places=3)
    weight_kg: Decimal | None = Field(None, ge=0, decimal_places=3) # NEW
    base_price: Decimal | None = Field(None, ge=0, decimal_places=2)
    compare_at_price: Decimal | None = Field(None, ge=0, decimal_places=2)
    cost_price: Decimal | None = Field(None, ge=0, decimal_places=2) # NEW
    quantity: int | None = Field(None, ge=0)
    allow_oversell: bool | None = None # NEW

    # Global Identifiers
    barcode: str | None = Field(None, max_length=255) # NEW
    hs_code: str | None = Field(None, max_length=64) # NEW

    attributes: dict[str, Any] | None = None
    status: str | None = Field(None, max_length=32)
    listing_readiness: ListingReadiness | None = None
    active: bool | None = None
    currency_code: str | None = Field(None, min_length=3, max_length=3)

    @field_validator("colour", "barcode", "hs_code", mode="before")
    @classmethod
    def _blank_colour_none_update(cls, v: object) -> str | None:
        if v is None:
            return None
        s = str(v).strip()
        return s or None

    @field_validator("currency_code", mode="before")
    @classmethod
    def _currency_upper_upd(cls, v: object) -> str | None:
        if v is None:
            return None
        s = str(v).strip().upper()
        return s if len(s) == 3 else None


class ProductRead(ProductBase):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    organisation_id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    created_by_user_id: uuid.UUID | None = None
    updated_by_user_id: uuid.UUID | None = None
    created_by_label: str | None = None
    updated_by_label: str | None = None
    images: list[ProductImageRead] = []
    brand_name: str | None = None  # set by API from ryunova_brands
    comment_count: int = 0
    marketplace_listings: list[ProductMarketplaceListingRead] = []


class ProductCommentCreate(BaseModel):
    body: str = Field(min_length=1, max_length=8000)

    @field_validator("body", mode="before")
    @classmethod
    def _strip_body(cls, v: object) -> str:
        s = str(v or "").strip()
        if not s:
            raise ValueError("Comment cannot be empty")
        return s


class ProductCommentRead(BaseModel):
    id: uuid.UUID
    product_id: uuid.UUID
    body: str
    created_at: datetime
    author_display_name: str


class ScrapePreviewRequest(BaseModel):
    url: HttpUrl
    source: Literal["shopify", "ebay"] = "shopify"


class ScrapePreviewResponse(BaseModel):
    """Mapped fields for product form prefill (client sends attributes on save)."""

    title: str | None = None
    description: str | None = None
    condition: ProductCondition = ProductCondition.new
    base_price: str | None = None
    compare_at_price: str | None = None
    quantity: int = 1
    model: str | None = None
    colour: str | None = None
    suggested_brand_name: str | None = None
    data_origin: str
    import_source_url: str


class ProductListPage(BaseModel):
    """Paginated product list (GET /products)."""

    items: list[ProductRead]
    total: int = Field(ge=0)
    page: int = Field(ge=1)
    page_size: int
    total_pages: int = Field(ge=1)
